using System.ComponentModel;

namespace Arena;
public enum Primitive_Result
{
	UNKNOWN,
	SUCCESS,
	SUCCESS_EMAIL_INVALID,
	KEYCLOAK,
	KEYCLOAK_ERROR,
	KEYCLOAK_NOT_CREATED,
	KEYCLOAK_TOKEN_ERROR,
	KEYCLOAK_ACCESS_TOKEN_NULL,
	KEYCLOAK_USERINFO_SUB_NULL,
	KEYCLOAK_ADMIN_TOKEN_ERROR,
	KEYCLOAK_USERINFO_ERROR,
	KEYCLOAK_AUTH_ERROR,
	DB_NEWUSER_ERROR,
	UNAPPROVED,
	NEED_VERIFICATION,
	SUCCESS_SEND_EMAIL_FAIL,
	EMAIL_ALREADY_EXISTS,
	
	[Description("You are not logged in")]
	LOGIN_REQUIRED,

	[Description("You are not admin")]
	ADMIN_REQUIRED,

	[Description("You do not own this resource")]
	MISSING_OWNERSHIP,
	
	[Description("This resource does not exist")]
	NOT_FOUND,


	REQUEST_COOLDOWN,
	CLAIM_KEYCLOAK_NOT_FOUND,
	REGISTER_ORGID_INVALID,
};

