using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;
using System.Linq;
using HotChocolate;
using HotChocolate.Types;

namespace Arena
{

	public enum Itemkind
	{
		UNKNOWN,
		IMAGE,
		VIDEO,
		TEXT
	}

	public static class Itemkindclass
	{
		public static Itemkind from_file_extenstion(string ext)
		{
			switch(ext)
			{
			case ".webp":
			case ".bmp":
			case ".gif":
			case ".jpg":
			case ".png":
				return Itemkind.IMAGE;
			case ".mp4":
			case ".mkv":
				return Itemkind.VIDEO;
			case ".txt":
				return Itemkind.TEXT;
			}
			return Itemkind.UNKNOWN;
		}
	}


	public class Fileitem
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
		public int id { get; set; }
		
		[GraphQLDescription("Autogenerated fields")]
		public DateTime time_created { get; set; }
		public DateTime time_modified { get; set; }
		public string name { get; set; }
		public string path { get; set; }
		public Itemkind kind { get; set; }
		public Record_Status record_status { get; set; }

		public virtual ICollection<Fileitem_User_Edge> fileitem_user_edges { get; set; }

	};


}