using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

using HotChocolate;

namespace Arena
{
	[GraphQLDescription("comprising one or more people and having a particular purpose.")]
	public class Organization
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
		public int id { get; set; }

		[GraphQLDescription("Autogenerated fields")]
		public DateTime time_created { get; set; }
		public DateTime time_modified { get; set; }
		
		//https://meta.cdq.com/Organization_registration_number_(Sweden)
		public String orgid { get; set; }
		public Country_Code_ISO_3166_1 country_code { get; set; }
		public String name { get; set; }
		public String address { get; set; }
		public String description { get; set; }
		public String image_logo { get; set; }
		public String phonenumber { get; set; }
		public String website { get; set; }
		public String email { get; set; }
		public Record_Status record_status { get; set; }

		[HotChocolate.Data.UseFiltering]
		public virtual ICollection<Organization_User_Edge> organization_user_edges { get; set; }
		public virtual ICollection<Organization_Course_Edge> organization_course_edges { get; set; }
		public virtual ICollection<Inquiry> inquiries { get; set; }
		public virtual ICollection<Course> courses { get; set; }
	}
}