using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;
using HotChocolate;

namespace Arena
{
	public class User
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
		public int id { get; set; }
		public Guid keycloak_guid { get; set; }

		public Record_Status record_status { get; set; }

		[GraphQLDescription("Autogenerated fields")]
		public DateTime time_created { get; set; }
		public DateTime time_modified { get; set; }

		public int preference { get; set; }

		public string username { get; set; }
		public string firstname { get; set; }
		public string lastname { get; set; }
		public string email { get; set; }
		public Country_Code_ISO_3166_1 preference_language { get; set; } = Country_Code_ISO_3166_1.SE;


		[HotChocolate.Data.UseFiltering]
		public virtual ICollection<Course_User_Edge> course_user_edges { get; set; }

		[HotChocolate.Data.UseFiltering]
		public virtual ICollection<Organization_User_Edge> organization_user_edges { get; set; }

		[HotChocolate.Data.UseFiltering]
		public virtual ICollection<Inquiry_User_Edge> inquiry_user_edges { get; set; }

		[HotChocolate.Data.UseFiltering]
		public virtual ICollection<Fileitem_User_Edge> fileitem_user_edges { get; set; }


		public virtual ICollection<User_Content_Edge> user_content_edges { get; set; }

	}
}